"""change column in messange

Revision ID: 119fdb551b1e
Revises: edafd657f910
Create Date: 2025-10-19 17:38:34.208215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119fdb551b1e'
down_revision: Union[str, Sequence[str], None] = 'edafd657f910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messanges', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messanges', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messanges', type_='foreignkey')
    op.drop_column('messanges', 'chat_id')
    # ### end Alembic commands ###
