"""Fixed comment table

Revision ID: 93bb0464c0c1
Revises: 9167f7cd191a
Create Date: 2025-10-05 11:55:24.041460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bb0464c0c1'
down_revision: Union[str, Sequence[str], None] = '9167f7cd191a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'comments', 'posts', ['post'], ['uuid'])
    op.create_unique_constraint(None, 'posts', ['uuid'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post')
    # ### end Alembic commands ###
