"""change column on chat

Revision ID: edafd657f910
Revises: d7c0d564b0fd
Create Date: 2025-10-19 10:20:58.770707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edafd657f910'
down_revision: Union[str, Sequence[str], None] = 'd7c0d564b0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user1_id', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('user2_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chats_from_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_to_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['user2_id'], ['id'])
    op.drop_column('chats', 'to_id')
    op.drop_column('chats', 'from_id')
    op.create_unique_constraint(None, 'messanges', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messanges', type_='unique')
    op.add_column('chats', sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_to_id_fkey'), 'chats', 'users', ['to_id'], ['id'])
    op.create_foreign_key(op.f('chats_from_id_fkey'), 'chats', 'users', ['from_id'], ['id'])
    op.drop_column('chats', 'user2_id')
    op.drop_column('chats', 'user1_id')
    # ### end Alembic commands ###
